for(i=0;i<12;i+=1)
{
if(instance_exists(JIQIREN[i]))
{
JIQIREN[i].gravity_direction=i*30+time
JIQIREN[i].gravity=0.5
}
}
with(other)
{
instance_destroy()
}
instance_destroy()
instance_create_depth(x,y,0,robotDie)
with(instance_create_depth(x,y,0,robotDie))
{
image_index=1
}
with(instance_create_depth(x,y,0,robotDie))
{
image_index=2
}

