if(xt=0)
{
with(instance_create_depth(x,y,depth,but_dust_yellow_bone))
{
image_index=1
gravity=0.3
hspeed=random_range(-5,5)
vspeed=random_range(-5,5)
xt=1
ang=choose(-3,3)
}
with(instance_create_depth(x,y,depth,but_dust_yellow_bone))
{
image_index=2
gravity=0.3
hspeed=random_range(-5,5)
vspeed=random_range(-5,5)
xt=1
ang=choose(-3,3)
}
}
instance_destroy()

