xt=0;
//audio_play_sound(ws,255,1);
page=0;
/*if(os_get_language()=="en"){
	if(date_get_timezone()!=timezone_utc){
		date_set_timezone(timezone_utc);
	}else{*/
		date_set_timezone(timezone_local);
	/*}
}*/
scale_x=2;
scale_y=2;
alpha=1;
isEndPage=1;
isStartPage=0;
line=-1;
//sew=12;
color=0;
colora=0;
GLang=Lang.Zh
