with(instance_create_depth(x,y,0,robotBlockDie))
{
image_index=0
image_blend=other.image_blend
}
with(instance_create_depth(x,y,0,robotBlockDie))
{
image_index=1
image_blend=other.image_blend
}
with(instance_create_depth(x,y,0,robotBlockDie))
{
image_index=2
image_blend=other.image_blend
}
with(instance_create_depth(x,y,0,robotBlockDie))
{
image_index=3
image_blend=other.image_blend
}
