if(xt="wall")
{
draw_sprite_ext(spr_IIIIII_IIII,0,x,y+124,1,1,ang,c_white,1)
draw_sprite_ext(spr_IIIIII_IIII,1,x,y+124,1,1,ang,col,1)
}

if(xt="bone" || xt="noone")
{
draw_self()
}
if(xt="bone")
{
draw_set_color(c_white)
draw_set_alpha(1)
draw_rectangle(x,y+40,x-line_x,y+46,0)
if(collision_rectangle(x,y+40,x-line_x,y+46,obj_soul,1,0))
{
with(obj_soul)
{
event_user(10)
}
}
}
if(xt!="bone" && xt!="noone")
{
draw_sprite_ext(sprite_index,3,x,y+yy,image_xscale,image_yscale,0,c_white,1)
draw_sprite_ext(sprite_index,4,x,y,image_xscale,image_yscale,0,c_white,1)
draw_sprite_ext(sprite_index,2,x,y,image_xscale,image_yscale,0,c_white,1)
}
if(xt="get")
{
draw_sprite_ext(spr_IIIIII_II,0,x,y+124,1,1,0,c_white,1)
}

if(xt="wall")
{
draw_set_color(col)
draw_line_width(x,y+124,x+lengthdir_x(1300,ang+180),y+lengthdir_y(1300,ang+180),5)
for(var XXXX=-2;XXXX<3;XXXX+=1)
{
if(collision_line(x+lengthdir_x(1+XXXX,ang+180),y+124+lengthdir_y(1+XXXX,ang+180),x+lengthdir_x(1300+XXXX,ang+180),y+lengthdir_y(1300+XXXX,ang+180),obj_soul,1,0))
{
if(col=global.blue)
{
with(obj_soul)
{
event_user(11)
}
}
if(col=c_orange)
{
with(obj_soul)
{
event_user(12)
}
}
}
}
}